import type { JapanRegionId } from "@/lib/map-config";

/** 都道府县日文名 → 地方区分 */
export const JAPAN_REGION_BY_PREFECTURE: Record<string, JapanRegionId> = {
  北海道: "hokkaido",
  青森県: "tohoku",
  岩手県: "tohoku",
  宮城県: "tohoku",
  秋田県: "tohoku",
  山形県: "tohoku",
  福島県: "tohoku",
  東京都: "kanto",
  神奈川県: "kanto",
  埼玉県: "kanto",
  千葉県: "kanto",
  茨城県: "kanto",
  栃木県: "kanto",
  群馬県: "kanto",
  愛知県: "chubu",
  静岡県: "chubu",
  長野県: "chubu",
  新潟県: "chubu",
  石川県: "chubu",
  富山県: "chubu",
  福井県: "chubu",
  岐阜県: "chubu",
  山梨県: "chubu",
  大阪府: "kinki",
  京都府: "kinki",
  兵庫県: "kinki",
  奈良県: "kinki",
  和歌山県: "kinki",
  滋賀県: "kinki",
  三重県: "kinki",
  広島県: "chugoku",
  岡山県: "chugoku",
  山口県: "chugoku",
  鳥取県: "chugoku",
  島根県: "chugoku",
  香川県: "shikoku",
  愛媛県: "shikoku",
  徳島県: "shikoku",
  高知県: "shikoku",
  福岡県: "kyushu",
  佐賀県: "kyushu",
  長崎県: "kyushu",
  熊本県: "kyushu",
  大分県: "kyushu",
  宮崎県: "kyushu",
  鹿児島県: "kyushu",
  沖縄県: "kyushu",
};

export function getJapanRegionId(prefectureName: string): JapanRegionId | null {
  return JAPAN_REGION_BY_PREFECTURE[prefectureName] ?? null;
}
